### ISSUE TITLE
Long execution time when running provided code

### ISSUE THREAD

**Issue by Kiligmzq6** [xybFight/NAR4TSP#2]
Hello,

Thank you for providing the code. I encountered an issue regarding the execution time when running the scripts. Specifically, it takes significantly longer than expected to complete, even with a machine that meets the required specifications.

Could you please provide insights into:

1. The expected runtime for the provided code?
2. Possible optimizations or recommendations to improve execution speed?
3. Whether there might be any dependencies or configurations that I should check to ensure the code runs efficiently?

Thank you for your help!

**Comment by xybFight** [comment]
Thank you for your attention. 

I assume you are referring to the "val.py" file. I have checked the code and rerun this file. There seems to be no problem in executing this file, and the inference time is about the same as the results given in my manuscript.

I don't use any special dependencies. Here is the version of these packages:
```bash
Python==3.8.12
torch==1.8.1
numpy==1.21.4
```

If you're using the same machine, i.e., with 8GB memory, my guess is that some programs are taking up some of the GPU memory. If so, you can set the "batch_size" to a smaller number.

If you have any question, please let me know.

Best regard!

**Comment by xybFight** [comment]
If you have no further questions, I'll close this issue.

Thank you again for your interest in our work.
